### ISSUE TITLE
Sending invalid file stream makes the response hang

### ISSUE THREAD

**Issue by emmettprexus** [fedirz/faster-whisper-server#164]
Thank you for the great work! I have a challenge in regards to error handling. In case I receive a stream that is not valid audio, the API seems to just hang instead of returning an error I can try and do my best to handle:

```javascript
        const openai = new OpenAI({
            baseURL: "http://localhost:8000/v1",
            apiKey: "none"
        });
        
        const transcription = await openai.audio.transcriptions.create({
            file: stream,
            model: "Systran/faster-whisper-small",
        });
```

From the docker logs I get:

```
2024-11-23 14:22:26 [2024-11-23 10:22:26.517] [ctranslate2] [thread 41] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.
2024-11-23 14:22:26 2024-11-23 10:22:26,712:INFO:faster_whisper_server.model_manager:_load:Model Systran/faster-whisper-small loaded in 10.75s
2024-11-23 14:22:26 2024-11-23 10:22:26,713:INFO:faster_whisper_server.model_manager:_decrement_ref:Model Systran/faster-whisper-small is idle, scheduling offload in 300s
2024-11-23 14:22:26 INFO:     172.20.0.1:52150 - "POST /v1/audio/transcriptions HTTP/1.1" 500 Internal Server Error
2024-11-23 14:22:26 ERROR:    Exception in ASGI application
2024-11-23 14:22:26 Traceback (most recent call last):
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
2024-11-23 14:22:26     result = await app(  # type: ignore[func-returns-value]
2024-11-23 14:22:26              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-11-23 14:22:26     return await self.app(scope, receive, send)
2024-11-23 14:22:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
2024-11-23 14:22:26     await super().__call__(scope, receive, send)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
2024-11-23 14:22:26     await self.middleware_stack(scope, receive, send)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
2024-11-23 14:22:26     raise exc
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
2024-11-23 14:22:26     await self.app(scope, receive, _send)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-11-23 14:22:26     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-11-23 14:22:26     raise exc
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-11-23 14:22:26     await app(scope, receive, sender)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
2024-11-23 14:22:26     await self.middleware_stack(scope, receive, send)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
2024-11-23 14:22:26     await route.handle(scope, receive, send)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
2024-11-23 14:22:26     await self.app(scope, receive, send)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
2024-11-23 14:22:26     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-11-23 14:22:26     raise exc
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-11-23 14:22:26     await app(scope, receive, sender)
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
2024-11-23 14:22:26     response = await f(request)
2024-11-23 14:22:26                ^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
2024-11-23 14:22:26     raw_response = await run_endpoint_function(
2024-11-23 14:22:26                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
2024-11-23 14:22:26     return await run_in_threadpool(dependant.call, **values)
2024-11-23 14:22:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
2024-11-23 14:22:26     return await anyio.to_thread.run_sync(func, *args)
2024-11-23 14:22:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-11-23 14:22:26     return await get_async_backend().run_sync_in_worker_thread(
2024-11-23 14:22:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
2024-11-23 14:22:26     return await future
2024-11-23 14:22:26            ^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 914, in run
2024-11-23 14:22:26     result = context.run(func, *args)
2024-11-23 14:22:26              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/faster_whisper_server/routers/stt.py", line 210, in transcribe_file
2024-11-23 14:22:26     segments, transcription_info = whisper.transcribe(
2024-11-23 14:22:26                                    ^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/faster_whisper/transcribe.py", line 319, in transcribe
2024-11-23 14:22:26     audio = decode_audio(audio, sampling_rate=sampling_rate)
2024-11-23 14:22:26             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "/root/faster-whisper-server/.venv/lib/python3.12/site-packages/faster_whisper/audio.py", line 46, in decode_audio
2024-11-23 14:22:26     with av.open(input_file, mode="r", metadata_errors="ignore") as container:
2024-11-23 14:22:26          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-23 14:22:26   File "av/container/core.pyx", line 420, in av.container.core.open
2024-11-23 14:22:26   File "av/container/core.pyx", line 266, in av.container.core.Container.__cinit__
2024-11-23 14:22:26   File "av/container/core.pyx", line 286, in av.container.core.Container.err_check
2024-11-23 14:22:26   File "av/error.pyx", line 326, in av.error.err_check
2024-11-23 14:22:26 av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input: 'None'
```

...And the request over the openai package never seems to complete.

**Comment by huzaifahj** [comment]
I have a similar issue. The API returns 500 with no information about what the error was. Even if it just returned this:

```
Invalid data found when processing input: 'None'
```

That would be useful.

**Comment by fedirz** [comment]
Will take a look

**Comment by emmettprexus** [comment]
Thanks a lot, @fedirz ! 

I think handing the API a .txt file or some invalid audio should result in a `400 Bad Request`. At least then I know to blame the user 😆

**Comment by emmettprexus** [comment]
Thank you, @fedirz <3
