### ISSUE TITLE
cannot work on arm64

### ISSUE THREAD

**Issue by kiron111** [fedirz/faster-whisper-server#20]
``` Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/soundfile.py", line 161, in <module>
    import _soundfile_data  # ImportError if this doesn't exist
    ^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_soundfile_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/soundfile.py", line 170, in <module>
    raise OSError('sndfile library not found using ctypes.util.find_library')
OSError: sndfile library not found using ctypes.util.find_library

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/faster-whisper-server/faster_whisper_server/main.py", line 29, in <module>
    from faster_whisper_server.asr import FasterWhisperASR
  File "/root/faster-whisper-server/faster_whisper_server/asr.py", line 7, in <module>
    from faster_whisper_server.audio import Audio
  File "/root/faster-whisper-server/faster_whisper_server/audio.py", line 7, in <module>
    import soundfile as sf
  File "/root/.cache/pypoetry/virtualenvs/non-package-mode-OS1lL15s-py3.12/lib/python3.12/site-packages/soundfile.py", line 192, in <module>
    _snd = _ffi.dlopen(_explicit_libname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory
```

I just build docker(just pull from fredirz's docker hub) for my arm64 computer (a RK3588 board), after I run the docker, it failed.
Becase I cannot launch container, so I cannot install the missing module/package to fix it....

**Comment by kiron111** [comment]
I solve it, just by not using directly the poetry, with building docker.
Thankyou again, for your projects, it helps me a lot

**Comment by randomradio** [comment]
Providing a working copy of Docker.cpu to run on arm64.

M1 Mac.

```
FROM ubuntu:22.04
# `ffmpeg` is installed because without it `gradio` won't work with mp3(possible others as well) files
# hadolint ignore=DL3008,DL3015,DL4006
RUN apt-get update && \
    apt-get install -y ffmpeg software-properties-common && \
    apt-get install -y libsndfile1 && \
    add-apt-repository ppa:deadsnakes/ppa && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3.12 python3.12-distutils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /root/faster-whisper-server
COPY requirements-dev.txt .
RUN --mount=from=ghcr.io/astral-sh/uv:latest,source=/uv,target=/bin/uv \
    uv pip install --system --python 3.12 --no-cache -r requirements-dev.txt
COPY ./faster_whisper_server ./faster_whisper_server
ENV WHISPER__MODEL=Systran/faster-whisper-medium.en
ENV WHISPER__INFERENCE_DEVICE=cpu
ENV WHISPER__COMPUTE_TYPE=int8
ENV UVICORN_HOST=0.0.0.0
ENV UVICORN_PORT=8000

EXPOSE 8000

CMD ["uvicorn", "faster_whisper_server.main:app"]
```
Build with:
` docker build -f Dockerfile.cpu -t faster-whisper-server .`

Simply start your container and VOILÀ.

**Comment by fedirz** [comment]
The latest version should be working on ARM

**Comment by kiron111** [comment]
> The latest version should be working on ARM

thankyou!!!
