### ISSUE TITLE
REST API response format only returns text. 

### ISSUE THREAD

**Issue by tavikano** [fedirz/faster-whisper-server#44]
REST API only outputs “text” format, can’t seem to output verbose_json based output even after configuring ENV. Are timestamped segments supported when calling the API?

**Comment by tavikano** [comment]
I’m now able to get the segments, thanks for such a great project!

**Comment by himekifee** [comment]
@tavikano Hi, could you please let me know what you have changed to make it return segments? Having the same problem.

**Comment by himekifee** [comment]
NVM. I was using new-api, and its audio endpoint implementation is buggy, causing a loss of segment info.

**Comment by fedirz** [comment]
Hey, was this a configuration issue or is there an issue with the server?

**Comment by himekifee** [comment]
It's an issue outside the scope of the faster-whisper-server. new-api is a router platform for LLMs and some other text2img, audio models. However, their audio endpoint implementation is not designed properly causing the drop of elements in the result. So it has nothing to do with this project.

**Comment by tavikano** [comment]
For anyone needing some context, If I remember correctly, the change that allowed the verbose_json to be enable through API was adding a the environment for value on the docker compose. Let me know if there are any other or questions about this.

**Comment by jtomchak** [comment]
> For anyone needing some context, If I remember correctly, the change that allowed the verbose_json to be enable through API was adding a the environment for value on the docker compose. Let me know if there are any other or questions about this.

curious what you set in the docker compose. I'm running everything from docker and it's working great, unless I set the response format to `verbose_json` 

```
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ERROR: Exception in ASGI application
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] Traceback (most recent call last):
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] result = await app( # type: ignore[func-returns-value]
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await self.app(scope, receive, send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/fastapi/applications.py", line 1054, in __call__
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await super().__call__(scope, receive, send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/applications.py", line 123, in __call__
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.middleware_stack(scope, receive, send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/errors.py", line 186, in __call__
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raise exc
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/errors.py", line 164, in __call__
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.app(scope, receive, _send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/cors.py", line 85, in __call__
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.app(scope, receive, send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raise exc
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await app(scope, receive, sender)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 756, in __call__
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.middleware_stack(scope, receive, send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 776, in app
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await route.handle(scope, receive, send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 297, in handle
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.app(scope, receive, send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 77, in app
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raise exc
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await app(scope, receive, sender)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 72, in app
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] response = await func(request)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 278, in app
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raw_response = await run_endpoint_function(
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await run_in_threadpool(dependant.call, **values)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await anyio.to_thread.run_sync(func, *args)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/anyio/to_thread.py", line 56, in run_sync
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await get_async_backend().run_sync_in_worker_thread(
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await future
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] result = context.run(func, *args)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/main.py", line 297, in transcribe_file
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return segments_to_response(segments, transcription_info, response_format)
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/main.py", line 180, in segments_to_response
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] TranscriptionVerboseJsonResponse.from_segments(segments, transcription_info).model_dump_json(),
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/server_models.py", line 54, in from_segments
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] words=Word.from_segments(segments),
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/core.py", line 26, in from_segments
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] assert segment.words is not None
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] AssertionError
```

**Comment by pomelio** [comment]
> > For anyone needing some context, If I remember correctly, the change that allowed the verbose_json to be enable through API was adding a the environment for value on the docker compose. Let me know if there are any other or questions about this.
> 
> curious what you set in the docker compose. I'm running everything from docker and it's working great, unless I set the response format to `verbose_json`
> 
> ```
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ERROR: Exception in ASGI application
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] Traceback (most recent call last):
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] result = await app( # type: ignore[func-returns-value]
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await self.app(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/fastapi/applications.py", line 1054, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await super().__call__(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/applications.py", line 123, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.middleware_stack(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/errors.py", line 186, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raise exc
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/errors.py", line 164, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.app(scope, receive, _send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/cors.py", line 85, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.app(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raise exc
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await app(scope, receive, sender)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 756, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.middleware_stack(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 776, in app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await route.handle(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 297, in handle
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.app(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 77, in app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await wrap_app_handling_exceptions(app, request)(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raise exc
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await app(scope, receive, sender)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 72, in app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] response = await func(request)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 278, in app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raw_response = await run_endpoint_function(
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await run_in_threadpool(dependant.call, **values)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/concurrency.py", line 42, in run_in_threadpool
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await anyio.to_thread.run_sync(func, *args)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/anyio/to_thread.py", line 56, in run_sync
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await get_async_backend().run_sync_in_worker_thread(
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await future
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/anyio/_backends/_asyncio.py", line 859, in run
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] result = context.run(func, *args)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/main.py", line 297, in transcribe_file
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return segments_to_response(segments, transcription_info, response_format)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/main.py", line 180, in segments_to_response
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] TranscriptionVerboseJsonResponse.from_segments(segments, transcription_info).model_dump_json(),
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/server_models.py", line 54, in from_segments
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] words=Word.from_segments(segments),
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/core.py", line 26, in from_segments
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] assert segment.words is not None
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] AssertionError
> ```

same as me

**Comment by tavikano** [comment]
@pomelio 
You probably want to cURL first and make sure you get what you want, the Async implementation you seem to be doing might be out of the scope of the original concern. The API is functioning as expected, I think this kind of verbose_json output was a recent feature implementation so check the releases and commits of the project.

**Comment by himekifee** [comment]
> > For anyone needing some context, If I remember correctly, the change that allowed the verbose_json to be enable through API was adding a the environment for value on the docker compose. Let me know if there are any other or questions about this.
> 
> curious what you set in the docker compose. I'm running everything from docker and it's working great, unless I set the response format to `verbose_json`
> 
> ```
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ERROR: Exception in ASGI application
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] Traceback (most recent call last):
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] result = await app( # type: ignore[func-returns-value]
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await self.app(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/fastapi/applications.py", line 1054, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await super().__call__(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/applications.py", line 123, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.middleware_stack(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/errors.py", line 186, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raise exc
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/errors.py", line 164, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.app(scope, receive, _send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/cors.py", line 85, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.app(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raise exc
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await app(scope, receive, sender)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 756, in __call__
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.middleware_stack(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 776, in app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await route.handle(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 297, in handle
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await self.app(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 77, in app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await wrap_app_handling_exceptions(app, request)(scope, receive, send)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raise exc
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] await app(scope, receive, sender)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 72, in app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] response = await func(request)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 278, in app
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] raw_response = await run_endpoint_function(
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await run_in_threadpool(dependant.call, **values)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/starlette/concurrency.py", line 42, in run_in_threadpool
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await anyio.to_thread.run_sync(func, *args)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/anyio/to_thread.py", line 56, in run_sync
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await get_async_backend().run_sync_in_worker_thread(
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return await future
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/usr/local/lib/python3.12/dist-packages/anyio/_backends/_asyncio.py", line 859, in run
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] result = context.run(func, *args)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/main.py", line 297, in transcribe_file
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] return segments_to_response(segments, transcription_info, response_format)
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/main.py", line 180, in segments_to_response
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] TranscriptionVerboseJsonResponse.from_segments(segments, transcription_info).model_dump_json(),
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/server_models.py", line 54, in from_segments
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] words=Word.from_segments(segments),
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] File "/root/faster-whisper-server/faster_whisper_server/core.py", line 26, in from_segments
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] assert segment.words is not None
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] ^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-08-16T23:24:47.640 app[e2866547f67648] ord [info] AssertionError
> ```

You may need something like [this](https://github.com/openai/openai-python/blob/435a5805ccbd5939a68f7f359ab72e937ef86e59/tests/api_resources/audio/test_transcriptions.py#L37). It would be a bug if verbose_json requires word-level timestamp_granularities, you can try if it works with it.

**Comment by jtomchak** [comment]
Ah. That’s a good call. If I add ‘stream=true’, I totally get the results back with no error. I’ll try a few other combinations and report back.
