### ISSUE TITLE
response_format = verbose_json error

### ISSUE THREAD

**Issue by FrancisVarga** [fedirz/faster-whisper-server#58]
Ill add the base_url to my open request and got this error:

Request:
```
client = OpenAI(api_key=environ().get("OPENAI_API_KEY"), 
                base_url="http://localhost:8000/v1/")

audio_file = open("data/84911634199_6551b8fc2da11c06f690b7ec_1722429823895.mp3", "rb")
transcript = client.audio.transcriptions.create(
    model="flyingleafe/faster-whisper-large-v3", 
    file=audio_file,
    response_format="verbose_json",
)
```

Error:
```
2024-08-20 01:53:40 INFO:     172.17.0.1:52180 - "POST /v1/audio/transcriptions HTTP/1.1" 500 Internal Server Error
2024-08-20 01:53:40 ERROR:    Exception in ASGI application
2024-08-20 01:53:40 Traceback (most recent call last):
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-08-20 01:53:40     result = await app(  # type: ignore[func-returns-value]
2024-08-20 01:53:40              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-08-20 01:53:40     return await self.app(scope, receive, send)
2024-08-20 01:53:40            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/fastapi/applications.py", line 1054, in __call__
2024-08-20 01:53:40     await super().__call__(scope, receive, send)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/applications.py", line 123, in __call__
2024-08-20 01:53:40     await self.middleware_stack(scope, receive, send)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/errors.py", line 186, in __call__
2024-08-20 01:53:40     raise exc
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/errors.py", line 164, in __call__
2024-08-20 01:53:40     await self.app(scope, receive, _send)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-08-20 01:53:40     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-20 01:53:40     raise exc
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-20 01:53:40     await app(scope, receive, sender)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 756, in __call__
2024-08-20 01:53:40     await self.middleware_stack(scope, receive, send)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 776, in app
2024-08-20 01:53:40     await route.handle(scope, receive, send)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 297, in handle
2024-08-20 01:53:40     await self.app(scope, receive, send)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 77, in app
2024-08-20 01:53:40     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-20 01:53:40     raise exc
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-20 01:53:40     await app(scope, receive, sender)
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 72, in app
2024-08-20 01:53:40     response = await func(request)
2024-08-20 01:53:40                ^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 278, in app
2024-08-20 01:53:40     raw_response = await run_endpoint_function(
2024-08-20 01:53:40                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-08-20 01:53:40     return await run_in_threadpool(dependant.call, **values)
2024-08-20 01:53:40            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-08-20 01:53:40     return await anyio.to_thread.run_sync(func, *args)
2024-08-20 01:53:40            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/anyio/to_thread.py", line 56, in run_sync
2024-08-20 01:53:40     return await get_async_backend().run_sync_in_worker_thread(
2024-08-20 01:53:40            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-08-20 01:53:40     return await future
2024-08-20 01:53:40            ^^^^^^^^^^^^
2024-08-20 01:53:40   File "/usr/local/lib/python3.12/dist-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-08-20 01:53:40     result = context.run(func, *args)
2024-08-20 01:53:40              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/root/faster-whisper-server/faster_whisper_server/main.py", line 297, in transcribe_file
2024-08-20 01:53:40     return segments_to_response(segments, transcription_info, response_format)
2024-08-20 01:53:40            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/root/faster-whisper-server/faster_whisper_server/main.py", line 180, in segments_to_response
2024-08-20 01:53:40     TranscriptionVerboseJsonResponse.from_segments(segments, transcription_info).model_dump_json(),
2024-08-20 01:53:40     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/root/faster-whisper-server/faster_whisper_server/server_models.py", line 54, in from_segments
2024-08-20 01:53:40     words=Word.from_segments(segments),
2024-08-20 01:53:40           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40   File "/root/faster-whisper-server/faster_whisper_server/core.py", line 26, in from_segments
2024-08-20 01:53:40     assert segment.words is not None
2024-08-20 01:53:40            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-20 01:53:40 AssertionError
```

**Comment by desher** [comment]
Confirmed, similar error when `response-format=verbose_json`

**Comment by ilkersigirci** [comment]
Same error, I hope it is fixed soon

**Comment by fedirz** [comment]
@bi1101 is correct, you do need to provide `timestamp_granularities[]` for it to work properly. This actually (unintentionally) mimics the behavior of OpenAI's API. 
```python
from openai import OpenAI

client = OpenAI()

audio_file = open("audio.wav", "rb")
transcript = client.audio.transcriptions.create(
    file=audio_file,
    model="whisper-1",
    # openai doesn't work. 5xx
    # response_format="verbose_json",
    # timestamp_granularities=["segment"],

    # openai doesn't work. 5xx
    # response_format="verbose_json",

    # openai doesn't work. 5xx
    # response_format="verbose_json",
    # timestamp_granularities=[],

    # openai works
    # response_format="verbose_json",
    # timestamp_granularities=["word"],

    # openai works. same as above
    # response_format="verbose_json",
    # timestamp_granularities=["word", "segment"],
)
print(transcript)
```

I do, however, think that my implemention should be changed (or at least a better error should be given) to not fail when `timestamp_granularities[]` isn't set.
